# Generated by Django 5.2.12 on 2026-03-13 16:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("sslcommerz", "SSLCommerz")],
                        db_index=True,
                        help_text="Payment gateway that sent the webhook",
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True, help_text="Type of webhook event", max_length=100
                    ),
                ),
                ("payload", models.JSONField(help_text="Raw webhook payload")),
                (
                    "processed",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this event has been processed",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if processing failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway", "-created_at"],
                        name="webhook_eve_gateway_168a19_idx",
                    ),
                    models.Index(
                        fields=["event_type", "processed"],
                        name="webhook_eve_event_t_f5eefa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[("stripe", "Stripe"), ("sslcommerz", "SSLCommerz")],
                        help_text="Payment gateway used",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        db_index=True,
                        help_text="Gateway transaction ID",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Payment amount",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="When payment was completed", null=True
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw gateway response"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        help_text="The invoice this payment is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invoices.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "db_table": "payments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invoice", "-created_at"],
                        name="payments_invoice_cf8e59_idx",
                    ),
                    models.Index(
                        fields=["gateway", "status"], name="payments_gateway_3ac0c5_idx"
                    ),
                    models.Index(
                        fields=["transaction_id"], name="payments_transac_a1f824_idx"
                    ),
                ],
            },
        ),
    ]
