# Generated by Django 5.2.12 on 2026-04-10 16:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantGatewaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webhook_public_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Opaque id used in webhook URL paths for this merchant",
                        unique=True,
                    ),
                ),
                ("stripe_enabled", models.BooleanField(default=False)),
                (
                    "stripe_publishable_key",
                    models.CharField(blank=True, max_length=255),
                ),
                ("stripe_secret_key_encrypted", models.TextField(blank=True)),
                ("stripe_webhook_secret_encrypted", models.TextField(blank=True)),
                ("sslcommerz_enabled", models.BooleanField(default=False)),
                ("sslcommerz_store_id", models.CharField(blank=True, max_length=255)),
                ("sslcommerz_store_password_encrypted", models.TextField(blank=True)),
                ("sslcommerz_is_live", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_gateway_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Merchant gateway settings",
                "verbose_name_plural": "Merchant gateway settings",
                "db_table": "merchant_gateway_settings",
            },
        ),
    ]
