# Generated by Django 5.2.12 on 2026-03-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Client full name", max_length=255),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Client email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Client phone number", max_length=20
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, help_text="Client company name", max_length=255
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Client address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The business user who owns this client",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "db_table": "clients",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="clients_user_id_2eb453_idx",
                    ),
                    models.Index(fields=["email"], name="clients_email_4c8bec_idx"),
                ],
            },
        ),
    ]
