# Generated by Django 5.2.12 on 2026-03-13 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_invoices",
                    models.IntegerField(
                        default=0, help_text="Total number of invoices"
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total revenue from paid invoices",
                        max_digits=12,
                    ),
                ),
                (
                    "paid_invoices",
                    models.IntegerField(default=0, help_text="Number of paid invoices"),
                ),
                (
                    "pending_invoices",
                    models.IntegerField(
                        default=0, help_text="Number of pending invoices"
                    ),
                ),
                (
                    "overdue_invoices",
                    models.IntegerField(
                        default=0, help_text="Number of overdue invoices"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="When analytics were last calculated"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The user these analytics belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice Analytics",
                "verbose_name_plural": "Invoice Analytics",
                "db_table": "invoice_analytics",
            },
        ),
    ]
